### ISSUE TITLE
Desactivar chequeo hardcore de bash

### ISSUE THREAD

**Issue by andres-blanco** [rlegene/bfa#1]
Estaría bueno sacar este chequeo para poder correr desde otros shells (por eg zsh)
https://github.com/rlegene/bfa/blob/c4fa470a646561db933a672c223291c34cbe634d/bin/libbfa.sh#L14-L15

Se puede agregar este Shebang para forzar la ejecución con bash en todo los scripts:
```bash
#!/usr/bin/env bash
```

**Comment by rlegene** [comment]
Puse ese check de bash porque realmente estoy usando trucos que no existe en sh y no se en que otros shells si funciona (p.ej ${var:2} ${var,,} ${#var} ).

Puedo cambiarlo si funciona en zsh, pero prefiero hacerlo un whitelist mas que un blacklist (agregar zsh si decis que funciona todo bien). Que te parece?

**Comment by rlegene** [comment]
He cambiado `libbfa.sh` para que usa `$BASH_VERSION`
