### ISSUE TITLE
Un par de comentarios.

### ISSUE THREAD

**Issue by 333333h1t** [rlegene/bfa#3]
Hola que tal? estuve viendo el código de las contratos un poco esto pero no entiendo la funcionalidad de este software. Es algo para votar, o algo así?

Estoy pagando impuestos para que esto exista, exijo saber para qué fue creado este software y de porqué hay una necidad de hacer que este basado en la blockchain, para llamar la atención?

También me gustaría saber, de donde van a sacar gente que mine si no hay una cryptocurrencia a arriba de esto, el estado mismo? pero si es así no tiene sentido que exista una blockchain.

Mira, yo no pienso poner nada a que mine algo que no sé para que existe y que no me va a pagar la luz que estoy gastando. Dudo mucho que alguien lo haga.

Por cierto, esto es un software Argentino, creo que tendría que estar todo en español, comúnmente es una mala práctica pero como viene del estado, y es nacional tendría que estarlo.

Perdonen un poco por la negatividad, sé que estan trabajando, pero yo también trabajo y una parte de lo que cobro va a al estado, especialmente cuando importo lago que la industria nacional Argentina no puede proveer y si que da la casualidad que sí es un desastre o tiene precio exagerado.

**Comment by rlegene** [comment]
Gracias por pagar tus impuestos.
Esto no es el foro para tus comentarios.
